### ISSUE TITLE
Broken link to "ambassador container" doc

### ISSUE THREAD

**Issue by candlerb** [awslabs/ecs-task-kite#4]
Link to "ambassador container" in README.md is broken

New location appears to be: https://docs.docker.com/engine/admin/ambassador_pattern_linking/

**Comment by samuelkarp** [comment]
Thanks!  I've opened https://github.com/awslabs/ecs-task-kite/pull/5 to fix this.

**Comment by samuelkarp** [comment]
Merged https://github.com/awslabs/ecs-task-kite/commit/8a57589fa7ac77d8f4bda0f933190baef63d8709.
